#!/bin/bash

#########################
#Author: Elena Galbally elenagal@stanford.edu
#########################

cd ~
cd code/sai/core/sai2-urdfreader/
echo ">>>>>>>>>>>>> sai2-urdfreader"
mkdir build && cd build && cmake .. && make -j4
echo ""

for repo in sai2-urdfreader sai2-model chai3d sai2-graphics sai2-simulation sai2-common sai2-primitives; do
    echo ">>>>>>>>>>>>>" ${repo}
    cd ../"${repo}/"
    rm -rfv build/ bin/
	mkdir build
	cd build
	cmake ..
	make -j4
    echo ""
done

echo "Build folders are now empty"